/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.DersRequest;
import ResponseModel.DataResponse;
import ResponseModel.DersResponse;
import ResponseModel.OgretmenSecResponse;
import com.google.gson.reflect.TypeToken;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author huseyin
 */
public class DersEditForm extends javax.swing.JDialog {

    private ArrayList<OgretmenSecList> ogretmen_list = new ArrayList<OgretmenSecList>();
    OgretmenSecList ogretmenSecList = new OgretmenSecList();
    List<OgretmenSecResponse> ogretmenSecResponseList;

    private Component backForm;

    private String id;
    private String ders_adi;
    private String kredi;
    private String donem;
    private String gun;
    private String saat;
    private String ogretmen_id;
    private String ad_soyad;
    private String kullanici_adi;

    /**
     * Creates new form OgrenciEditForm
     */
    public DersEditForm(java.awt.Frame parent, boolean modal, Component backForm) {
        super(parent, modal);
        initComponents();

        ogretmen_listesi_olustur();

        this.backForm = backForm;
        this.id = "0";
    }

    public void ogretmen_listesi_olustur() {
        String json = Lib.jsonResponse("ogretmen_sec_list", new DataRequest());
        DataResponse<OgretmenSecResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<OgretmenSecResponse>>() {
        }.getType());

        ogretmenSecResponseList = dataResponse.getData(this);
        if (ogretmenSecResponseList != null) {
            for (OgretmenSecResponse ogretmenSecResponse : ogretmenSecResponseList) {

                ogretmenSecList = new OgretmenSecList();
                ogretmenSecList.ekle("ogretmen_id", ogretmenSecResponse.getOgretmenId());
                ogretmenSecList.ekle("ad_soyad", ogretmenSecResponse.getAdSoyad());
                ogretmenSecList.ekle("kullanici_adi", ogretmenSecResponse.getKullaniciAdi());
                ogretmen_list.add(ogretmenSecList);

            }
        }

        String[] isimler = new String[ogretmen_list.size()];

        for (int i = 0; i < ogretmen_list.size(); i++) {
            isimler[i] = ogretmen_list.get(i).goster("kullanici_adi");
        }

        ComboBoxModel ogretmenKullaniciAdi = new DefaultComboBoxModel(isimler);
        edt_kullanici_adi_combobox.setModel(ogretmenKullaniciAdi);

    }

    public DersEditForm(java.awt.Frame parent, boolean modal, Component backForm, String id, String ders_adi, String kredi, String donem, String gun, String saat, String ogretmen_id, String ad_soyad, String kullanici_adi) {
        super(parent, modal);
        initComponents();

        ogretmen_listesi_olustur();

        this.backForm = backForm;
        this.id = id;
        this.ders_adi = ders_adi;
        this.kredi = kredi;
        this.donem = donem;
        this.gun = gun;
        this.saat = saat;
        this.ogretmen_id = ogretmen_id;
        this.ad_soyad = ad_soyad;
        this.kullanici_adi = kullanici_adi;

        edt_ders_adi.setText(ders_adi);
        edt_kredi.setText(kredi);
        edt_donem.setText(donem);
        edt_gun.setText(gun);
        edt_saat.setText(saat);
        edt_ogretmen_id.setText(ogretmen_id);
        edt_ad_soyad.setText(ad_soyad);
        edt_kullanici_adi_combobox.setSelectedItem(kullanici_adi);
    }

    private DersEditForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kaydet = new javax.swing.JButton();
        edt_ders_adi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt_kredi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edt_donem = new javax.swing.JTextField();
        edt_gun = new javax.swing.JTextField();
        edt_saat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        edt_ad_soyad = new javax.swing.JTextField();
        edt_ogretmen_id = new javax.swing.JTextField();
        edt_kullanici_adi_combobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 150, 0, 0));

        btn_kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/save.png"))); // NOI18N
        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        jLabel1.setText("Ders Adı");

        jLabel2.setText("Kredi");

        jLabel3.setText("Donem");

        jLabel4.setText("Gun");

        jLabel5.setText("Saat");

        jLabel7.setText("Kullanıcı Adı (Ogr.)");

        jLabel8.setText("Ad Soyad (Ogr.)");

        jLabel9.setText("ID (Ogretmen)");

        edt_ad_soyad.setEditable(false);

        edt_ogretmen_id.setEditable(false);

        edt_kullanici_adi_combobox.setEditable(true);
        edt_kullanici_adi_combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                edt_kullanici_adi_comboboxİtemStateChanged(evt);
            }
        });
        edt_kullanici_adi_combobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_kullanici_adi_comboboxMouseClicked(evt);
            }
        });
        edt_kullanici_adi_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_kullanici_adi_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_kredi, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(edt_gun)
                            .addComponent(edt_ders_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_donem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_saat, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_ad_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(edt_ogretmen_id)
                            .addComponent(edt_kullanici_adi_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_ders_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(edt_kullanici_adi_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_kredi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edt_ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_donem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edt_ogretmen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_saat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_kaydet)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed

        insert_update_akademik();
        this.setVisible(false);
        this.backForm.setVisible(false);
        this.backForm.setVisible(true);


    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void edt_kullanici_adi_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_kullanici_adi_comboboxActionPerformed

    }//GEN-LAST:event_edt_kullanici_adi_comboboxActionPerformed

    private void edt_kullanici_adi_comboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_kullanici_adi_comboboxMouseClicked

    }//GEN-LAST:event_edt_kullanici_adi_comboboxMouseClicked

    private void edt_kullanici_adi_comboboxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_edt_kullanici_adi_comboboxİtemStateChanged

        for (int i = 0; i < ogretmen_list.size(); i++) {
            if (ogretmen_list.get(i).goster("kullanici_adi").equals(edt_kullanici_adi_combobox.getSelectedItem().toString())) {
                edt_ad_soyad.setText(ogretmen_list.get(i).goster("ad_soyad"));
                edt_ogretmen_id.setText(ogretmen_list.get(i).goster("ogretmen_id"));
            }
        }

    }//GEN-LAST:event_edt_kullanici_adi_comboboxİtemStateChanged

    private void insert_update_akademik() {

        DersRequest dersRequest = new DersRequest();
        dersRequest.setDersId(this.id);
        dersRequest.setDersAdi(edt_ders_adi.getText());
        dersRequest.setKredi(edt_kredi.getText());
        dersRequest.setDonem(edt_donem.getText());
        dersRequest.setGun(edt_gun.getText());
        dersRequest.setSaati(edt_saat.getText());
        dersRequest.setOgretmenId(edt_ogretmen_id.getText());
        dersRequest.setAdSoyad(edt_ad_soyad.getText());
        dersRequest.setKullaniciAdi(edt_kullanici_adi_combobox.getSelectedItem().toString());

        String json = Lib.jsonResponse("insert_update_ders", new DataRequest(dersRequest));
        DataResponse<DersResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<DersResponse>>() {
        }.getType());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DersEditForm dialog = new DersEditForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JTextField edt_ad_soyad;
    private javax.swing.JTextField edt_ders_adi;
    private javax.swing.JTextField edt_donem;
    private javax.swing.JTextField edt_gun;
    private javax.swing.JTextField edt_kredi;
    private javax.swing.JComboBox<String> edt_kullanici_adi_combobox;
    private javax.swing.JTextField edt_ogretmen_id;
    private javax.swing.JTextField edt_saat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
