/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.DonemSecimiRequest;
import RequestModel.IzinRequest;
import ResponseModel.DataResponse;
import ResponseModel.DonemSecimiResponse;
import ResponseModel.IzinResponse;
import com.google.gson.reflect.TypeToken;
import java.util.List;

/**
 *
 * @author huseyin
 */
public class DonemSecimiForm extends javax.swing.JDialog {
    
    List<DonemSecimiResponse> donemSecimiResponseList;

    /**
     * Creates new form DersIzinForm
     */
    public DonemSecimiForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        rd_doldur();

    }

    public void rd_doldur() {
        
        DonemSecimiRequest donemSecimiRequest = new DonemSecimiRequest();
        
        String json = Lib.jsonResponse("donem_secimi_durum", new DataRequest(donemSecimiRequest));
        DataResponse<DonemSecimiResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<DonemSecimiResponse>>() {
        }.getType());

        donemSecimiResponseList = dataResponse.getData(this);
        String donem = null;
        if (donemSecimiResponseList != null) {
            for (DonemSecimiResponse donemSecimiResponse : donemSecimiResponseList) {
                donem = donemSecimiResponse.getDonem();
            }
        }
        
        if (donem.equals("bahar")) {
            rd_bahar.setSelected(true);
            rd_guz.setSelected(false);
        }
        else if (donem.equals("güz")) {
            rd_bahar.setSelected(false);
            rd_guz.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rd_guz = new javax.swing.JRadioButton();
        rd_bahar = new javax.swing.JRadioButton();
        btn_kaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 250, 0, 0));

        buttonGroup1.add(rd_guz);
        rd_guz.setText("GÜZ");
        rd_guz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_guzActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_bahar);
        rd_bahar.setText("BAHAR");

        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kaydet)
                    .addComponent(rd_bahar)
                    .addComponent(rd_guz))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(rd_guz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_bahar)
                .addGap(18, 18, 18)
                .addComponent(btn_kaydet)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed

        izin_kaydet();
        
        this.setVisible(false);

    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void rd_guzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_guzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_guzActionPerformed

    public void izin_kaydet() {
        DonemSecimiRequest donemSecimiRequest = new DonemSecimiRequest();
        
        if (rd_guz.isSelected()) {
            donemSecimiRequest.setDurum("güz");
        }
        else {
            donemSecimiRequest.setDurum("bahar");
        }
        

        String json = Lib.jsonResponse("update_donem_secimi", new DataRequest(donemSecimiRequest));
        DataResponse<DonemSecimiResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<DonemSecimiResponse>>() {
        }.getType());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DersIzinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DersIzinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DersIzinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DersIzinForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DersIzinForm dialog = new DersIzinForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rd_bahar;
    private javax.swing.JRadioButton rd_guz;
    // End of variables declaration//GEN-END:variables
}
