package Otomasyon;

import Lib.Lib;
import Lib.Public;
import RequestModel.DataRequest;
import RequestModel.LoginRequest;
import ResponseModel.DataResponse;
import ResponseModel.KullaniciAkademikResponse;
import ResponseModel.KullaniciIdariResponse;
import ResponseModel.KullaniciOgrenciResponse;
import com.google.gson.reflect.TypeToken;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    private String secili_rd;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.secili_rd = "";
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Giris_Butonları = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt_kullanici_adi = new javax.swing.JTextField();
        edt_parola = new javax.swing.JPasswordField();
        rd_ogrenci = new javax.swing.JRadioButton();
        rd_akademisyen = new javax.swing.JRadioButton();
        rd_idari = new javax.swing.JRadioButton();
        btn_giris_yap = new javax.swing.JButton();
        btn_kapat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş Yap");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        jLabel1.setText("Kullanici Adı");

        jLabel2.setText("Parola");

        Giris_Butonları.add(rd_ogrenci);
        rd_ogrenci.setText("Öğrenci");
        rd_ogrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_ogrenciActionPerformed(evt);
            }
        });

        Giris_Butonları.add(rd_akademisyen);
        rd_akademisyen.setText("Akademik");
        rd_akademisyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_akademisyenActionPerformed(evt);
            }
        });

        Giris_Butonları.add(rd_idari);
        rd_idari.setText("İdari");
        rd_idari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_idariActionPerformed(evt);
            }
        });

        btn_giris_yap.setText("Giriş Yap");
        btn_giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giris_yapActionPerformed(evt);
            }
        });

        btn_kapat.setText("Kapat");
        btn_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kapatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rd_idari)
                    .addComponent(rd_akademisyen)
                    .addComponent(rd_ogrenci)
                    .addComponent(edt_parola)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_giris_yap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_kapat))
                    .addComponent(edt_kullanici_adi))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edt_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rd_ogrenci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_akademisyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_idari)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giris_yap)
                    .addComponent(btn_kapat))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("uu_logo.png"));
    }
    
    private void giris_yap(String kullanici_adi, String parola, String kullanici_tur) {

        RequestModel.LoginRequest loginRequest = new LoginRequest();
        loginRequest.setKullaniciAdi(kullanici_adi);
        loginRequest.setParola(parola);
        loginRequest.setKullaniciTip(kullanici_tur);

        String json = Lib.jsonResponse("login", new DataRequest(loginRequest));
        if (kullanici_tur.equals("ogrenci")) {

            DataResponse<KullaniciOgrenciResponse> dataKullaniciResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<KullaniciOgrenciResponse>>() {
            }.getType());
            List<KullaniciOgrenciResponse> kullaniciResponsesList = dataKullaniciResponse.getData(this);
            if (kullaniciResponsesList != null) {
                Public.ogrenciResponse = kullaniciResponsesList.get(0);

                OgrenciMainForm ogrenciForm = new OgrenciMainForm(edt_kullanici_adi.getText());
                ogrenciForm.setVisible(true);
                this.setVisible(false);
            }

        } else if (kullanici_tur.equals("akademisyen")) {

            DataResponse<KullaniciAkademikResponse> dataKullaniciResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<KullaniciAkademikResponse>>() {
            }.getType());
            List<KullaniciAkademikResponse> kullaniciResponsesList = dataKullaniciResponse.getData(this);
            if (kullaniciResponsesList != null) {
                Public.akademikResponse = kullaniciResponsesList.get(0);

                AkademikMainForm akademikForm = new AkademikMainForm(edt_kullanici_adi.getText());
                akademikForm.setVisible(true);
                this.setVisible(false);
            }

        } else if (kullanici_tur.equals("idari")) {

            DataResponse<KullaniciIdariResponse> dataKullaniciResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<KullaniciIdariResponse>>() {
            }.getType());
            List<KullaniciIdariResponse> kullaniciResponsesList = dataKullaniciResponse.getData(this);
            if (kullaniciResponsesList != null) {
                Public.idariResponse = kullaniciResponsesList.get(0);

                IdariMainForm idariForm = new IdariMainForm();
                idariForm.setVisible(true);
                this.setVisible(false);
            }

        }

    }

    private void btn_giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giris_yapActionPerformed

        if (secili_rd.equals("")) {
            JOptionPane.showMessageDialog(this, "Lütfen Kullanıcı Tipi Seçiniz");
        } else {
            giris_yap(edt_kullanici_adi.getText(), new String(edt_parola.getPassword()), secili_rd);
        }

    }//GEN-LAST:event_btn_giris_yapActionPerformed

    private void rd_ogrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_ogrenciActionPerformed
        if (rd_ogrenci.isSelected()) {
            this.secili_rd = "ogrenci";
        } else {
            this.secili_rd = "";
        }
    }//GEN-LAST:event_rd_ogrenciActionPerformed

    private void rd_akademisyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_akademisyenActionPerformed

        if (rd_akademisyen.isSelected()) {
            this.secili_rd = "akademisyen";
        } else {
            this.secili_rd = "";
        }

    }//GEN-LAST:event_rd_akademisyenActionPerformed

    private void rd_idariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_idariActionPerformed

        if (rd_idari.isSelected()) {
            this.secili_rd = "idari";
        } else {
            this.secili_rd = "";
        }

    }//GEN-LAST:event_rd_idariActionPerformed

    private void btn_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kapatActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btn_kapatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Giris_Butonları;
    private javax.swing.JButton btn_giris_yap;
    private javax.swing.JButton btn_kapat;
    private javax.swing.JTextField edt_kullanici_adi;
    private javax.swing.JPasswordField edt_parola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rd_akademisyen;
    private javax.swing.JRadioButton rd_idari;
    private javax.swing.JRadioButton rd_ogrenci;
    // End of variables declaration//GEN-END:variables
}
