/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.NotGirisiRequest;
import ResponseModel.DataResponse;
import ResponseModel.NotGirisiResponse;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huseyin
 */
public class NotGirisiForm extends javax.swing.JDialog {

    DefaultTableModel defaultTableModel;
    List<NotGirisiResponse> notGirisiResponseList;

    private String kullanici_adi;
    private String secili_ders;

    /**
     * Creates new form NotGirisiForm
     */
    public NotGirisiForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public NotGirisiForm(java.awt.Frame parent, boolean modal, String kullanici_adi, String secili_ders) {
        super(parent, modal);
        initComponents();

        this.kullanici_adi = kullanici_adi;
        this.secili_ders = secili_ders;

        not_girisi_liste();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_notlar = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Not Girişi");
        setBounds(new java.awt.Rectangle(350, 100, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Not Girişi");

        tbl_notlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÖĞRENCİ NO", "VİZE", "FİNAL", "BÜTÜNLEME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_notlar);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/save.png"))); // NOI18N
        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/close.png"))); // NOI18N
        jButton2.setText("Vazgeç");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        defaultTableModel = (DefaultTableModel) tbl_notlar.getModel();

        boolean kayıtKontrol = false;

        for (int i = 0; i < tbl_notlar.getRowCount(); i++) {

            float _vize, _final, _butunleme;

            try {
                _vize = Float.parseFloat(defaultTableModel.getValueAt(i, 1).toString());
                _final = Float.parseFloat(defaultTableModel.getValueAt(i, 2).toString());
                _butunleme = Float.parseFloat(defaultTableModel.getValueAt(i, 3).toString());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Verileri Sadece Sayı Girebilirsiniz");
                break;
            }

            if ((_vize > 100 || _vize < 0) || (_final > 100 || _final < 0) || (_butunleme > 100 || _butunleme < 0)) {
                JOptionPane.showMessageDialog(this, "Hatalı Not Girişi");
                break;
            } else {
                kayıtKontrol = true;
            }

        }

        if (kayıtKontrol) {

            for (int i = 0; i < tbl_notlar.getRowCount(); i++) {

                float _vize, _final, _butunleme;
                String ogrenci_no;
                _vize = Float.parseFloat(defaultTableModel.getValueAt(i, 1).toString());
                _final = Float.parseFloat(defaultTableModel.getValueAt(i, 2).toString());
                _butunleme = Float.parseFloat(defaultTableModel.getValueAt(i, 3).toString());
                ogrenci_no = defaultTableModel.getValueAt(i, 0).toString();
                
                ders_giris_update(ogrenci_no, this.secili_ders, _vize, _final, _butunleme);
                
            }

            kayıtKontrol = false;
        }
        
        this.setVisible(false);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void ders_giris_update(String ogrenci_no, String ders_adi, float _vize, float _final, float _butunleme) {
        
        NotGirisiRequest notGirisiRequest = new NotGirisiRequest();
        notGirisiRequest.setDersAdi(ders_adi);
        notGirisiRequest.setOgrenciNo(ogrenci_no);
        notGirisiRequest.setVize(String.valueOf(_vize));
        notGirisiRequest.setFinal(String.valueOf(_final));
        notGirisiRequest.setButunleme(String.valueOf(_butunleme));

        String json = Lib.jsonResponse("insert_update_not_girisi", new DataRequest(notGirisiRequest));
        DataResponse<NotGirisiResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<NotGirisiResponse>>() {
        }.getType());
        
    }
    
    public void not_girisi_liste() {

        defaultTableModel = (DefaultTableModel) tbl_notlar.getModel();

        NotGirisiRequest notGirisiRequest = new NotGirisiRequest();
        notGirisiRequest.setKullaniciAdi(this.kullanici_adi);
        notGirisiRequest.setDersAdi(this.secili_ders);

        String json = Lib.jsonResponse("not_girisi", new DataRequest(notGirisiRequest));
        DataResponse<NotGirisiResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<NotGirisiResponse>>() {
        }.getType());

        notGirisiResponseList = dataResponse.getData(this);
        if (notGirisiResponseList != null) {
            defaultTableModel.setRowCount(0);
            for (NotGirisiResponse notGirisiResponse : notGirisiResponseList) {
                Object[] objects = {
                    notGirisiResponse.getOgrenciNo(),
                    notGirisiResponse.getVize(),
                    notGirisiResponse.getFinal(),
                    notGirisiResponse.getButunleme()
                };
                defaultTableModel.addRow(objects);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotGirisiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotGirisiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotGirisiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotGirisiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotGirisiForm dialog = new NotGirisiForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_notlar;
    // End of variables declaration//GEN-END:variables
}
