/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.OgrenciRequest;
import ResponseModel.DataResponse;
import ResponseModel.OgrenciResponse;
import com.google.gson.reflect.TypeToken;
import java.awt.Component;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huseyin
 */
public class OgrenciListForm extends javax.swing.JInternalFrame {

    List<OgrenciResponse> ogrenciResponseList;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form OgrenciListForm
     */

    private Component backForm;

    public OgrenciListForm(Component backForm) {
        initComponents();

        this.backForm = backForm;

        Toolkit tk = Toolkit.getDefaultToolkit();
        int withSize = ((int) tk.getScreenSize().getWidth());
        int heightSize = ((int) tk.getScreenSize().getHeight()) - 150;
        this.setSize(withSize, heightSize);

        defaultTableModel = (DefaultTableModel) tbl_ogrenci_list.getModel();

        ogrenciList();

    }

    public void ogrenciList() {
        String filtre = "%" + edt_filtre.getText() + "%";
        OgrenciRequest ogrenciRequest = new OgrenciRequest();
        ogrenciRequest.setFiltre(filtre);

        String json = Lib.jsonResponse("ogrenci_list", new DataRequest(ogrenciRequest));
        DataResponse<OgrenciResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<OgrenciResponse>>() {
        }.getType());

        ogrenciResponseList = dataResponse.getData(this);
        if (ogrenciResponseList != null) {
            defaultTableModel.setRowCount(0);
            for (OgrenciResponse calisanResponse : ogrenciResponseList) {
                Object[] objects = {
                    calisanResponse.getId(),
                    calisanResponse.getNo(),
                    calisanResponse.getAdSoyad(),
                    calisanResponse.getTc(),
                    calisanResponse.getSifre(),
                    calisanResponse.getTelefon(),
                    calisanResponse.getDogumTarihi(),
                    calisanResponse.getMail(),
                    calisanResponse.getAdres(),
                    calisanResponse.getBolum(),
                    calisanResponse.getSinif(),
                    calisanResponse.getIl(),
                    calisanResponse.getIlce()
                };
                defaultTableModel.addRow(objects);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btn_kapat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ogrenci_list = new javax.swing.JTable();
        btn_ekle = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_guncelle = new javax.swing.JButton();
        edt_filtre = new javax.swing.JTextField();
        btn_filtrele = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Öğrenci Listesi");
        setNormalBounds(new java.awt.Rectangle(100, 50, 140, 0));
        setPreferredSize(new java.awt.Dimension(1370, 600));

        btn_kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/close.png"))); // NOI18N
        btn_kapat.setText("Kapat");
        btn_kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kapatActionPerformed(evt);
            }
        });

        tbl_ogrenci_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NO", "AD SOYAD", "TC", "ŞİFRE", "TELEFON", "DOĞUM TARİHİ", "MAİL", "ADRES", "BOLUM", "SINIF", "İL", "İLÇE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_ogrenci_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ogrenci_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ogrenci_list);

        btn_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/add.png"))); // NOI18N
        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        btn_sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/delete.png"))); // NOI18N
        btn_sil.setText("Sil");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/update.png"))); // NOI18N
        btn_guncelle.setText("Güncelle");
        btn_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guncelleActionPerformed(evt);
            }
        });

        btn_filtrele.setText("Filtrele");
        btn_filtrele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtreleActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btn_kapat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_ekle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_sil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_guncelle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(edt_filtre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_filtrele, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(edt_filtre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_filtrele)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_filtre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_filtrele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kapat)
                    .addComponent(btn_ekle)
                    .addComponent(btn_sil)
                    .addComponent(btn_guncelle))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kapatActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_btn_kapatActionPerformed

    private void ogrenci_sil() {

        String id = defaultTableModel.getValueAt(tbl_ogrenci_list.getSelectedRow(), 0).toString();

        OgrenciRequest ogrenciRequest = new OgrenciRequest();
        ogrenciRequest.setId(id);
        String json = Lib.jsonResponse("delete_ogrenci", new DataRequest(ogrenciRequest));
        DataResponse<OgrenciResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<OgrenciResponse>>() {
        }.getType());

        ogrenciResponseList = dataResponse.getData(this);
        if (ogrenciResponseList != null) {
            ogrenciList();
        }

    }

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        if (tbl_ogrenci_list.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(backForm, "Satır Seçiniz!");
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(backForm, "Silmek İstediğinize Emin misiniz?", "Uyarı", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                ogrenci_sil();
            }
        }

    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed

        OgrenciEditForm ogrenciEditForm = new OgrenciEditForm(null, true, this);
        ogrenciEditForm.show();
        ogrenciList();

    }//GEN-LAST:event_btn_ekleActionPerformed

    private void ogrenciGuncelle() {
        if (tbl_ogrenci_list.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen Öğrenci Seçiniz!");
        } else {

            int row = tbl_ogrenci_list.getSelectedRow();

            String id = defaultTableModel.getValueAt(row, 0).toString();
            String no = defaultTableModel.getValueAt(row, 1).toString();
            String ad_soyad = defaultTableModel.getValueAt(row, 2).toString();
            String tc = defaultTableModel.getValueAt(row, 3).toString();
            String sifre = defaultTableModel.getValueAt(row, 4).toString();
            String telefon = defaultTableModel.getValueAt(row, 5).toString();
            String dogum_tarihi = defaultTableModel.getValueAt(row, 6).toString();
            String mail = defaultTableModel.getValueAt(row, 7).toString();
            String adres = defaultTableModel.getValueAt(row, 8).toString();
            String bolum = defaultTableModel.getValueAt(row, 9).toString();
            String sinif = defaultTableModel.getValueAt(row, 10).toString();
            String il = defaultTableModel.getValueAt(row, 11).toString();
            String ilce = defaultTableModel.getValueAt(row, 12).toString();

            OgrenciEditForm ogrenciEditForm = new OgrenciEditForm(null, true, this, id, no, ad_soyad, tc, sifre, telefon, dogum_tarihi, mail, adres, bolum, sinif, il, ilce);
            ogrenciEditForm.show();
            ogrenciList();
        }

    }

    private void btn_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guncelleActionPerformed
        ogrenciGuncelle();
    }//GEN-LAST:event_btn_guncelleActionPerformed

    private void btn_filtreleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtreleActionPerformed
        if (edt_filtre.getText() != "") {
            ogrenciList();
        }

    }//GEN-LAST:event_btn_filtreleActionPerformed

    private void tbl_ogrenci_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ogrenci_listMouseClicked

        if (evt.getClickCount() == 2) {
            ogrenciGuncelle();
        }

    }//GEN-LAST:event_tbl_ogrenci_listMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_filtrele;
    private javax.swing.JButton btn_guncelle;
    private javax.swing.JButton btn_kapat;
    private javax.swing.JButton btn_sil;
    private javax.swing.JTextField edt_filtre;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ogrenci_list;
    // End of variables declaration//GEN-END:variables
}
