/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.OgrenciRequest;
import RequestModel.OgretmenKimlikRequest;
import ResponseModel.DataResponse;
import ResponseModel.OgrenciResponse;
import ResponseModel.OgretmenKimlikResponse;
import com.google.gson.reflect.TypeToken;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author huseyin
 */
public class OgretmenKimlikForm extends javax.swing.JDialog {
    
    private String kullanici_adi;

    /**
     * Creates new form OgretmenKimlikForm
     */
    public OgretmenKimlikForm(java.awt.Frame parent, boolean modal, String kullanici_adi) {
        super(parent, modal);
        initComponents();
        
        this.kullanici_adi = kullanici_adi;
        
        bilgileri_getir();
    }

    public void bilgileri_getir(){
        List<OgretmenKimlikResponse> ogretmenKimlikResponseList;
        
        OgretmenKimlikRequest ogretmenKimlikRequest = new OgretmenKimlikRequest();
        ogretmenKimlikRequest.setKullaniciAdi(this.kullanici_adi);

        String json = Lib.jsonResponse("ogretmen_kimlik_list", new DataRequest(ogretmenKimlikRequest));
        DataResponse<OgretmenKimlikResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<OgretmenKimlikResponse>>() {
        }.getType());

        ogretmenKimlikResponseList = dataResponse.getData(this);
        if (ogretmenKimlikResponseList != null) {
            for (OgretmenKimlikResponse ogretmenKimlikResponse : ogretmenKimlikResponseList) {
                    lbl_ad_soyad.setText(ogretmenKimlikResponse.getAdSoyad());
                    lbl_brans.setText(ogretmenKimlikResponse.getBrans());
                    lbl_tc.setText(ogretmenKimlikResponse.getTc());
                    lbl_telefon.setText(ogretmenKimlikResponse.getTelefon());
            }
        }
    }
    
    private OgretmenKimlikForm(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ad_soyad = new javax.swing.JLabel();
        lbl_tc = new javax.swing.JLabel();
        lbl_brans = new javax.swing.JLabel();
        lbl_telefon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Ad Soyad :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Tc :    ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Branş :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Telefon : ");

        lbl_ad_soyad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_ad_soyad.setForeground(new java.awt.Color(0, 0, 102));
        lbl_ad_soyad.setText("edt_ad_soyad");

        lbl_tc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_tc.setForeground(new java.awt.Color(0, 0, 102));
        lbl_tc.setText("edt_tc");

        lbl_brans.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_brans.setForeground(new java.awt.Color(0, 0, 102));
        lbl_brans.setText("edt_brans");

        lbl_telefon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_telefon.setForeground(new java.awt.Color(0, 0, 102));
        lbl_telefon.setText("edt_telefon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_telefon)
                    .addComponent(lbl_brans)
                    .addComponent(lbl_tc)
                    .addComponent(lbl_ad_soyad))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_ad_soyad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_tc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_brans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_telefon))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgretmenKimlikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgretmenKimlikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgretmenKimlikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgretmenKimlikForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OgretmenKimlikForm dialog = new OgretmenKimlikForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_ad_soyad;
    private javax.swing.JLabel lbl_brans;
    private javax.swing.JLabel lbl_tc;
    private javax.swing.JLabel lbl_telefon;
    // End of variables declaration//GEN-END:variables
}
