/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Otomasyon;

import Lib.Lib;
import RequestModel.DataRequest;
import RequestModel.OgrenciRequest;
import ResponseModel.DataResponse;
import ResponseModel.OgrenciResponse;
import com.google.gson.reflect.TypeToken;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author huseyin
 */
public class OgrenciEditForm extends javax.swing.JDialog {

    private Component backForm;

    private String id;
    private String no;
    private String ad_soyad;
    private String tc;
    private String sifre;
    private String telefon;
    private String dogum_tarihi;
    private String mail;
    private String adres;
    private String bolum;
    private String sınıf;
    private String il;
    private String ilce;

    /**
     * Creates new form OgrenciEditForm
     */
    public OgrenciEditForm(java.awt.Frame parent, boolean modal, Component backForm) {
        super(parent, modal);
        initComponents();

        this.backForm = backForm;
        this.id = "0";
    }

    public OgrenciEditForm(java.awt.Frame parent, boolean modal, Component backForm, String id, String no, String ad_soyad, String tc, String sifre, String telefon, String dogum_tarihi, String mail, String adres, String bolum, String sınıf, String il, String ilce) {
        super(parent, modal);
        initComponents();
        this.backForm = backForm;
        this.id = id;
        this.no = no;
        this.ad_soyad = ad_soyad;
        this.tc = tc;
        this.sifre = sifre;
        this.telefon = telefon;
        this.dogum_tarihi = dogum_tarihi;
        this.mail = mail;
        this.adres = adres;
        this.bolum = bolum;
        this.sınıf = sınıf;
        this.il = il;
        this.ilce = ilce;
        
        edt_no.setText(no);
        edt_ad_soyad.setText(ad_soyad);
        edt_tc.setText(tc);
        edt_sifre.setText(sifre);
        edt_telefon.setText(telefon);
        edt_dogum_tarihi.setText(dogum_tarihi);
        edt_mail.setText(mail);
        edt_adres.setText(adres);
        edt_bolum.setText(bolum);
        edt_il.setText(il);
        edt_sinif.setText(sınıf);
        edt_ilce.setText(ilce);
    }

    private OgrenciEditForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kaydet = new javax.swing.JButton();
        edt_no = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edt_ad_soyad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        edt_tc = new javax.swing.JTextField();
        edt_sifre = new javax.swing.JTextField();
        edt_telefon = new javax.swing.JTextField();
        edt_dogum_tarihi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        edt_mail = new javax.swing.JTextField();
        edt_adres = new javax.swing.JTextField();
        edt_bolum = new javax.swing.JTextField();
        edt_sinif = new javax.swing.JTextField();
        edt_il = new javax.swing.JTextField();
        edt_ilce = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(350, 150, 0, 0));

        btn_kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Otomasyon/save.png"))); // NOI18N
        btn_kaydet.setText("Kaydet");
        btn_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kaydetActionPerformed(evt);
            }
        });

        jLabel1.setText("No");

        jLabel2.setText("Ad Soyad");

        jLabel3.setText("Tc");

        jLabel4.setText("Sifre");

        jLabel5.setText("Telefon");

        jLabel6.setText("Doğum Tarihi");

        jLabel7.setText("Mail");

        jLabel8.setText("Adres");

        jLabel9.setText("Bölüm");

        jLabel10.setText("Sınıf");

        jLabel11.setText("İl");

        jLabel12.setText("İlçe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edt_ad_soyad, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(edt_sifre)
                    .addComponent(edt_dogum_tarihi)
                    .addComponent(edt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_kaydet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edt_mail)
                            .addComponent(edt_adres)
                            .addComponent(edt_bolum)
                            .addComponent(edt_sinif, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edt_il)
                            .addComponent(edt_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(edt_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edt_bolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edt_sinif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(edt_il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edt_dogum_tarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edt_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(btn_kaydet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kaydetActionPerformed

        

            insert_update_ogrenci();
            this.setVisible(false);
            this.backForm.setVisible(false);
            this.backForm.setVisible(true);
        

    }//GEN-LAST:event_btn_kaydetActionPerformed

    private void insert_update_ogrenci() {
        OgrenciRequest ogrenciRequest = new OgrenciRequest();
        ogrenciRequest.setId(this.id);
        ogrenciRequest.setNo(edt_no.getText());
        ogrenciRequest.setAdSoyad(edt_ad_soyad.getText());
        ogrenciRequest.setTc(edt_tc.getText());
        ogrenciRequest.setSifre(edt_sifre.getText());
        ogrenciRequest.setTelefon(edt_telefon.getText());
        ogrenciRequest.setDogumTarihi(edt_dogum_tarihi.getText());
        ogrenciRequest.setMail(edt_mail.getText());
        ogrenciRequest.setAdres(edt_adres.getText());
        ogrenciRequest.setBolum(edt_bolum.getText());
        ogrenciRequest.setSinif(edt_sinif.getText());
        ogrenciRequest.setIl(edt_il.getText());
        ogrenciRequest.setIlce(edt_ilce.getText());

        String json = Lib.jsonResponse("insert_update_ogrenci", new DataRequest(ogrenciRequest));
        DataResponse<OgrenciResponse> dataResponse = Lib.gson.fromJson(json, new TypeToken<DataResponse<OgrenciResponse>>() {
        }.getType());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OgrenciEditForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OgrenciEditForm dialog = new OgrenciEditForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kaydet;
    private javax.swing.JTextField edt_ad_soyad;
    private javax.swing.JTextField edt_adres;
    private javax.swing.JTextField edt_bolum;
    private javax.swing.JTextField edt_dogum_tarihi;
    private javax.swing.JTextField edt_il;
    private javax.swing.JTextField edt_ilce;
    private javax.swing.JTextField edt_mail;
    private javax.swing.JTextField edt_no;
    private javax.swing.JTextField edt_sifre;
    private javax.swing.JTextField edt_sinif;
    private javax.swing.JTextField edt_tc;
    private javax.swing.JTextField edt_telefon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
